version: '3'
services:
  mysql-boilerplate:
    image: mysql:5.7
    container_name: mysql-boilerplate
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: development
    volumes:
      - mysql_data:/var/lib/mysql

  boilerplate:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: boilerplate
    ports:
      - "3000:3000"
    depends_on:
      - mysql-boilerplate
    env_file:
      - .env
    volumes:
      - .:/usr/src/app:ro # Modo somente leitura, para evitar conflitos
      - /usr/src/app/node_modules

volumes:
  mysql_data:
